"""Generate docs/capability_matrix.md from code (never hand-edited).

Every table row is derived from the runtime objects themselves —
``LevelStructureSpec.supports_backend`` and ``NoiseModel.validate_for`` —
so the matrix cannot rot relative to the code.

Usage:
    uv run python docs/_scripts/build_capability_matrix.py        # rewrite
    uv run python docs/_scripts/build_capability_matrix.py --check  # CI diff
"""

from __future__ import annotations

import sys
from pathlib import Path

PRESETS = ("01", "1r", "01r", "analog_3", "rb87_7")
BACKENDS = ("exact", "mps", "gputn", "peps", "stabilizer")
OUT_PATH = Path(__file__).resolve().parents[1] / "capability_matrix.md"

YES, NO = "yes", "—"


def _level_structure_table() -> list[str]:
    from ryd_gate import level_structure

    lines = [
        "| level structure | " + " | ".join(BACKENDS) + " |",
        "|---" * (len(BACKENDS) + 1) + "|",
    ]
    for name in PRESETS:
        spec = level_structure(name)
        cells = [YES if spec.supports_backend(b) else NO for b in BACKENDS]
        lines.append(f"| `{name}` | " + " | ".join(cells) + " |")
    return lines


def _noise_table() -> list[str]:
    from ryd_gate import NoiseModel

    probes = {
        "detuning / amplitude / local RIN / position (Monte Carlo)": NoiseModel(
            detuning_sigma_rad_per_us=0.01
        ),
        "rydberg / intermediate decay (construction-time)": NoiseModel(rydberg_decay=True),
        "state-prep / readout / temperature / waist (data only)": NoiseModel(
            state_prep_error=0.01
        ),
    }
    lines = [
        "| noise group | " + " | ".join(BACKENDS) + " |",
        "|---" * (len(BACKENDS) + 1) + "|",
    ]
    for label, model in probes.items():
        cells = []
        for backend in BACKENDS:
            issues = model.validate_for(backend=backend, level_structure="rb87_7", n_atoms=2)
            cells.append(YES if not issues else NO)
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    return lines


def build_matrix() -> str:
    sections = [
        ("# Capability Matrix", [
            "",
            "Generated by `docs/_scripts/build_capability_matrix.py` — do not edit by hand.",
            "Regenerate with `uv run python docs/_scripts/build_capability_matrix.py`.",
            "",
        ]),
        ("## Level structure × backend", _level_structure_table()),
        ("## NoiseModel runtime support by backend", _noise_table()),
    ]
    parts: list[str] = []
    for title, lines in sections:
        parts.append(title)
        parts.extend(lines)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    text = build_matrix()
    if "--check" in sys.argv:
        current = OUT_PATH.read_text() if OUT_PATH.exists() else ""
        if current != text:
            print(f"{OUT_PATH} is stale; regenerate it.", file=sys.stderr)
            return 1
        print("capability matrix is up to date")
        return 0
    OUT_PATH.write_text(text)
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
