"""Reproduce the effective-CWE gap comparison used in ``MWIS.tex``.

The script diagonalizes the two-domain-wall Hamiltonian on an L-shaped
configuration graph.  The baseline uses endpoint detuning only.  The dynamic
corridor protocol additionally implements

    V_cat = -Lambda P_xlead + t P_xentrance,

which is generated by local detunings on the existing ``G_x`` and
``m_x+1`` atoms.  It writes only the curated manuscript figure; numerical
arrays are printed to stdout and are not persisted.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import matplotlib
import numpy as np
from scipy.linalg import eigh
from scipy.optimize import minimize_scalar

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402


@dataclass(frozen=True)
class CWEModel:
    points: tuple[tuple[int, int], ...]
    hopping: np.ndarray
    target_boundary: np.ndarray
    target_lead: np.ndarray
    target_entrance: np.ndarray


def build_cwe_model(length: int, width: int) -> CWEModel:
    """Return the calibrated CWE domain-wall graph in units where ``t=1``."""
    points = tuple(
        (x, y)
        for x in range(1, length + 1)
        for y in range(1, length + 1)
        if not (x > width and y > width)
    )
    index = {point: site for site, point in enumerate(points)}
    adjacency = np.zeros((len(points), len(points)), dtype=float)
    for point, site in index.items():
        for neighbor in ((point[0] + 1, point[1]), (point[0], point[1] + 1)):
            if neighbor in index:
                other = index[neighbor]
                adjacency[site, other] = adjacency[other, site] = 1.0

    # The CWE gadget adds one simultaneous-domain-wall hopping.
    first = index[(width + 1, width)]
    second = index[(width, width + 1)]
    adjacency[first, second] = adjacency[second, first] = 1.0

    return CWEModel(
        points=points,
        hopping=-adjacency,
        target_boundary=np.asarray([x == length for x, _ in points], dtype=float),
        target_lead=np.asarray([x > width for x, _ in points], dtype=float),
        target_entrance=np.asarray([x == width + 1 for x, _ in points], dtype=float),
    )


def two_lowest(
    model: CWEModel,
    endpoint_weight: float,
    corridor_strength: float,
    entrance_penalty: float,
    with_vectors: bool = False,
) -> tuple[np.ndarray, np.ndarray | None]:
    diagonal = (
        -endpoint_weight * model.target_boundary
        - corridor_strength * model.target_lead
        + entrance_penalty * model.target_entrance
    )
    hamiltonian = model.hopping.copy()
    hamiltonian[np.diag_indices_from(hamiltonian)] = diagonal
    if with_vectors:
        values, vectors = eigh(
            hamiltonian, subset_by_index=[0, 1], driver="evr"
        )
        return values, vectors
    values = eigh(
        hamiltonian,
        subset_by_index=[0, 1],
        eigvals_only=True,
        driver="evr",
    )
    return values, None


def minimum_endpoint_gap(
    model: CWEModel,
    corridor_strength: float,
    entrance_penalty: float,
) -> tuple[float, float, np.ndarray]:
    """Minimize the gap over a target-boundary detuning in ``[0, 3t]``."""

    def gap(weight: float) -> float:
        values, _ = two_lowest(
            model, weight, corridor_strength, entrance_penalty
        )
        return float(values[1] - values[0])

    coarse_weights = np.linspace(0.0, 3.0, 121)
    coarse_gaps = np.asarray([gap(weight) for weight in coarse_weights])
    center = int(np.argmin(coarse_gaps))
    lower = coarse_weights[max(center - 2, 0)]
    upper = coarse_weights[min(center + 2, len(coarse_weights) - 1)]
    optimum = minimize_scalar(
        gap,
        bounds=(lower, upper),
        method="bounded",
        options={"xatol": 1.0e-13, "maxiter": 500},
    )
    values, vectors = two_lowest(
        model,
        float(optimum.x),
        corridor_strength,
        entrance_penalty,
        with_vectors=True,
    )
    assert vectors is not None
    return float(values[1] - values[0]), float(optimum.x), vectors[:, 0]


def coordinate_marginal(
    model: CWEModel, state: np.ndarray, length: int
) -> np.ndarray:
    marginal = np.zeros(length, dtype=float)
    for amplitude, (x, _) in zip(state, model.points, strict=True):
        marginal[x - 1] += abs(amplitude) ** 2
    return marginal


def run(output: Path, width: int) -> None:
    lengths = np.asarray([8, 10, 12, 16, 20, 24, 28, 32, 36, 40, 48])
    baseline_gaps = []
    dynamic_gaps = []
    baseline_states: dict[int, tuple[CWEModel, np.ndarray, float]] = {}
    dynamic_states: dict[int, tuple[CWEModel, np.ndarray, float]] = {}

    corridor_strength = 2.0
    entrance_penalty = 1.0
    certified_threshold = 3.0 - 2.0 * np.cos(np.pi / (width + 1))
    if corridor_strength <= certified_threshold or entrance_penalty != 1.0:
        raise ValueError("chosen catalyst does not satisfy the analytic certificate")
    for length in lengths:
        model = build_cwe_model(int(length), width)
        baseline = minimum_endpoint_gap(model, 0.0, 0.0)
        dynamic = minimum_endpoint_gap(
            model, corridor_strength, entrance_penalty
        )
        baseline_gaps.append(baseline[0])
        dynamic_gaps.append(dynamic[0])
        if length == 40:
            baseline_states[int(length)] = (model, baseline[2], baseline[1])
            dynamic_states[int(length)] = (model, dynamic[2], dynamic[1])

    baseline_gaps = np.asarray(baseline_gaps)
    dynamic_gaps = np.asarray(dynamic_gaps)
    exponential_fit = np.polyfit(
        lengths[lengths >= 12], np.log(baseline_gaps[lengths >= 12]), 1
    )
    power_fit = np.polyfit(
        np.log(lengths[lengths >= 20]),
        np.log(dynamic_gaps[lengths >= 20]),
        1,
    )

    print("# L  baseline_min_gap  dynamic_min_gap")
    for length, baseline, dynamic in zip(
        lengths, baseline_gaps, dynamic_gaps, strict=True
    ):
        print(f"{length:3d}  {baseline:.12e}  {dynamic:.12e}")
    print(f"baseline exponential rate alpha={-exponential_fit[0]:.6f}")
    print(f"dynamic finite-size power z={-power_fit[0]:.6f}")
    print(
        "no-bound-state certificate: "
        f"kappa={corridor_strength:.6f} > {certified_threshold:.6f}"
    )

    figure, axes = plt.subplots(1, 2, figsize=(7.25, 3.05))
    axis = axes[0]
    axis.semilogy(
        lengths,
        baseline_gaps,
        "o",
        color="#D55E00",
        label="endpoint-only",
    )
    axis.semilogy(
        lengths,
        dynamic_gaps,
        "s",
        color="#0072B2",
        label="dynamic corridor",
    )
    dense_lengths = np.linspace(12, 48, 200)
    axis.semilogy(
        dense_lengths,
        np.exp(np.polyval(exponential_fit, dense_lengths)),
        "--",
        color="#D55E00",
        linewidth=1.0,
        label=rf"$e^{{-{(-exponential_fit[0]):.2f}L}}$ fit",
    )
    axis.semilogy(
        dense_lengths,
        np.exp(power_fit[1]) * dense_lengths ** power_fit[0],
        "--",
        color="#0072B2",
        linewidth=1.0,
        label=rf"$L^{{-{(-power_fit[0]):.2f}}}$ fit",
    )
    axis.set_xlabel(r"domain-wall length $L$")
    axis.set_ylabel(r"minimum gap $\delta E_m/t$")
    axis.set_title("(a) Endpoint sweep")
    axis.legend(frameon=False, fontsize=7)
    axis.grid(alpha=0.2)

    length = 40
    baseline_model, baseline_state, baseline_weight = baseline_states[length]
    dynamic_model, dynamic_state, dynamic_weight = dynamic_states[length]
    coordinate = np.arange(1, length + 1)
    axes[1].semilogy(
        coordinate,
        coordinate_marginal(baseline_model, baseline_state, length) + 1.0e-14,
        color="#D55E00",
        label=rf"endpoint-only ($w/t={baseline_weight:.2f}$)",
    )
    axes[1].semilogy(
        coordinate,
        coordinate_marginal(dynamic_model, dynamic_state, length) + 1.0e-14,
        color="#0072B2",
        label=rf"dynamic ($w/t={dynamic_weight:.2f}$)",
    )
    axes[1].axvline(width + 0.5, color="0.5", linestyle=":", linewidth=1.0)
    axes[1].set_xlabel(r"horizontal domain-wall coordinate $j_x$")
    axes[1].set_ylabel(r"marginal probability $p(j_x)$")
    axes[1].set_title(r"(b) Ground state at $\delta E_m$, $L=40$")
    axes[1].legend(frameon=False, fontsize=7)
    axes[1].grid(alpha=0.2)

    figure.tight_layout(w_pad=1.2)
    output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output, bbox_inches="tight")
    plt.close(figure)
    print(f"wrote {output}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("manuscripts/figures/mwis_dynamic_detuning_gap.pdf"),
    )
    parser.add_argument("--width", type=int, default=3)
    return parser.parse_args()


if __name__ == "__main__":
    arguments = parse_args()
    run(arguments.output, arguments.width)
